### ISSUE TITLE
Test difference in _subEncoding() methods in Cio encoder

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/nupic.fluent#79]
Method `"df"` uses document frequency scores of terms, and method `"keyword"` takes the union of the terms. Which results in more accurate classifications?

**Comment by akhilaananthram** [comment]
the comments that the cio encoder can't encode are usually just a few words and they are pretty rare in comparison to the number of comments that exist.  The most common phrase that doesn't have an encoding is "n a". I wasn't really able to see a notable difference between the two encoding fallback methods.
